import Post from "constants/interfaces/post.interface";

const posts: Post[] = [
  {
    id: "p_000001",
    title: "This is a very very very long title 1",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque sequi praesentium rerum!",
    content:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque sequi praesentium rerum! Ex, quam. Nam quisquam deserunt harum pariatur aliquam mollitia, quis expedita deleniti non vel, quia omnis ad aperiam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur est incidunt molestiae animi tempore harum expedita tempora ratione nostrum tenetur provident aspernatur vitae quod, necessitatibus temporibus ad, aliquid minima laudantium. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci quibusdam, qui assumenda ratione quisquam alias beatae in repudiandae aliquam tempore atque voluptas nesciunt pariatur voluptatibus sit nisi earum consequuntur saepe!",
    author: "John Doe",
    imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeAMripmaQGG7SvrVGI_j7HbCu1454HDiEoA&usqp=CAU",
    keywords: [],
    tags: ["JavaScript"],
    createdDate: "Wed Mar 23 2022 14:42:57 GMT+0700 (Indochina Time) {}",
    updatedDate: "Wed Mar 23 2022 14:42:57 GMT+0700 (Indochina Time) {}",
    reaction: {
      like: 0,
      love: 1,
      unicorn: 1,
      share: 4,
    },
    comments: [],
  },
  {
    id: "p_000002",
    title: "This is a very very very long title 2",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque sequi praesentium rerum!",
    content:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque sequi praesentium rerum! Ex, quam. Nam quisquam deserunt harum pariatur aliquam mollitia, quis expedita deleniti non vel, quia omnis ad aperiam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur est incidunt molestiae animi tempore harum expedita tempora ratione nostrum tenetur provident aspernatur vitae quod, necessitatibus temporibus ad, aliquid minima laudantium. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci quibusdam, qui assumenda ratione quisquam alias beatae in repudiandae aliquam tempore atque voluptas nesciunt pariatur voluptatibus sit nisi earum consequuntur saepe!",
    author: "John Doe",
    imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeAMripmaQGG7SvrVGI_j7HbCu1454HDiEoA&usqp=CAU",
    keywords: [],
    tags: ["JavaScript"],
    createdDate: "Wed Mar 23 2022 14:42:57 GMT+0700 (Indochina Time) {}",
    updatedDate: "Wed Mar 23 2022 14:42:57 GMT+0700 (Indochina Time) {}",
    reaction: {
      like: 0,
      love: 1,
      unicorn: 1,
      share: 4,
    },
    comments: [],
  },
  {
    id: "p_000003",
    title: "This is a very very very long title 3",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque sequi praesentium rerum!",
    content:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque sequi praesentium rerum! Ex, quam. Nam quisquam deserunt harum pariatur aliquam mollitia, quis expedita deleniti non vel, quia omnis ad aperiam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur est incidunt molestiae animi tempore harum expedita tempora ratione nostrum tenetur provident aspernatur vitae quod, necessitatibus temporibus ad, aliquid minima laudantium. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci quibusdam, qui assumenda ratione quisquam alias beatae in repudiandae aliquam tempore atque voluptas nesciunt pariatur voluptatibus sit nisi earum consequuntur saepe!",
    author: "John Doe",
    imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeAMripmaQGG7SvrVGI_j7HbCu1454HDiEoA&usqp=CAU",
    keywords: [],
    tags: ["JavaScript"],
    createdDate: "Wed Mar 23 2022 14:42:57 GMT+0700 (Indochina Time) {}",
    updatedDate: "Wed Mar 23 2022 14:42:57 GMT+0700 (Indochina Time) {}",
    reaction: {
      like: 0,
      love: 1,
      unicorn: 1,
      share: 4,
    },
    comments: [],
  },
  {
    id: "p_000004",
    title: "This is a very very very long title 4",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque sequi praesentium rerum!",
    content:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque sequi praesentium rerum! Ex, quam. Nam quisquam deserunt harum pariatur aliquam mollitia, quis expedita deleniti non vel, quia omnis ad aperiam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur est incidunt molestiae animi tempore harum expedita tempora ratione nostrum tenetur provident aspernatur vitae quod, necessitatibus temporibus ad, aliquid minima laudantium. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci quibusdam, qui assumenda ratione quisquam alias beatae in repudiandae aliquam tempore atque voluptas nesciunt pariatur voluptatibus sit nisi earum consequuntur saepe!",
    author: "John Doe",
    imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeAMripmaQGG7SvrVGI_j7HbCu1454HDiEoA&usqp=CAU",
    keywords: [],
    tags: ["JavaScript"],
    createdDate: "Wed Mar 23 2022 14:42:57 GMT+0700 (Indochina Time) {}",
    updatedDate: "Wed Mar 23 2022 14:42:57 GMT+0700 (Indochina Time) {}",
    reaction: {
      like: 0,
      love: 1,
      unicorn: 1,
      share: 4,
    },
    comments: [],
  },
  {
    id: "p_000005",
    title: "This is a very very very long title 5",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque sequi praesentium rerum!",
    content:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque sequi praesentium rerum! Ex, quam. Nam quisquam deserunt harum pariatur aliquam mollitia, quis expedita deleniti non vel, quia omnis ad aperiam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur est incidunt molestiae animi tempore harum expedita tempora ratione nostrum tenetur provident aspernatur vitae quod, necessitatibus temporibus ad, aliquid minima laudantium. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci quibusdam, qui assumenda ratione quisquam alias beatae in repudiandae aliquam tempore atque voluptas nesciunt pariatur voluptatibus sit nisi earum consequuntur saepe!",
    author: "John Doe",
    imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeAMripmaQGG7SvrVGI_j7HbCu1454HDiEoA&usqp=CAU",
    keywords: [],
    tags: ["JavaScript"],
    createdDate: "Wed Mar 23 2022 14:42:57 GMT+0700 (Indochina Time) {}",
    updatedDate: "Wed Mar 23 2022 14:42:57 GMT+0700 (Indochina Time) {}",
    reaction: {
      like: 0,
      love: 1,
      unicorn: 1,
      share: 4,
    },
    comments: [],
  },
  {
    id: "p_000006",
    title: "This is a very very very long title 6",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque sequi praesentium rerum!",
    content:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque sequi praesentium rerum! Ex, quam. Nam quisquam deserunt harum pariatur aliquam mollitia, quis expedita deleniti non vel, quia omnis ad aperiam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur est incidunt molestiae animi tempore harum expedita tempora ratione nostrum tenetur provident aspernatur vitae quod, necessitatibus temporibus ad, aliquid minima laudantium. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci quibusdam, qui assumenda ratione quisquam alias beatae in repudiandae aliquam tempore atque voluptas nesciunt pariatur voluptatibus sit nisi earum consequuntur saepe!",
    author: "John Doe",
    imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeAMripmaQGG7SvrVGI_j7HbCu1454HDiEoA&usqp=CAU",
    keywords: [],
    tags: ["JavaScript"],
    createdDate: "Wed Mar 23 2022 14:42:57 GMT+0700 (Indochina Time) {}",
    updatedDate: "Wed Mar 23 2022 14:42:57 GMT+0700 (Indochina Time) {}",
    reaction: {
      like: 0,
      love: 1,
      unicorn: 1,
      share: 4,
    },
    comments: [],
  },
  {
    id: "p_000007",
    title: "This is a very very very long title 7",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque sequi praesentium rerum!",
    content:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque sequi praesentium rerum! Ex, quam. Nam quisquam deserunt harum pariatur aliquam mollitia, quis expedita deleniti non vel, quia omnis ad aperiam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur est incidunt molestiae animi tempore harum expedita tempora ratione nostrum tenetur provident aspernatur vitae quod, necessitatibus temporibus ad, aliquid minima laudantium. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci quibusdam, qui assumenda ratione quisquam alias beatae in repudiandae aliquam tempore atque voluptas nesciunt pariatur voluptatibus sit nisi earum consequuntur saepe!",
    author: "John Doe",
    imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeAMripmaQGG7SvrVGI_j7HbCu1454HDiEoA&usqp=CAU",
    keywords: [],
    tags: ["JavaScript"],
    createdDate: "Wed Mar 23 2022 14:42:57 GMT+0700 (Indochina Time) {}",
    updatedDate: "Wed Mar 23 2022 14:42:57 GMT+0700 (Indochina Time) {}",
    reaction: {
      like: 0,
      love: 1,
      unicorn: 1,
      share: 4,
    },
    comments: [],
  },
  {
    id: "p_000008",
    title: "This is a very very very long title 8",
    description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque sequi praesentium rerum!",
    content:
      "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque sequi praesentium rerum! Ex, quam. Nam quisquam deserunt harum pariatur aliquam mollitia, quis expedita deleniti non vel, quia omnis ad aperiam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur est incidunt molestiae animi tempore harum expedita tempora ratione nostrum tenetur provident aspernatur vitae quod, necessitatibus temporibus ad, aliquid minima laudantium. Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci quibusdam, qui assumenda ratione quisquam alias beatae in repudiandae aliquam tempore atque voluptas nesciunt pariatur voluptatibus sit nisi earum consequuntur saepe!",
    author: "John Doe",
    imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeAMripmaQGG7SvrVGI_j7HbCu1454HDiEoA&usqp=CAU",
    keywords: [],
    tags: ["JavaScript"],
    createdDate: "Wed Mar 23 2022 14:42:57 GMT+0700 (Indochina Time) {}",
    updatedDate: "Wed Mar 23 2022 14:42:57 GMT+0700 (Indochina Time) {}",
    reaction: {
      like: 0,
      love: 1,
      unicorn: 1,
      share: 4,
    },
    comments: [],
  },
];

export default posts;
